export const COURSE_SUGGESTIONS = [
  "Linear Algebra",
  "Calculus I",
  "Calculus II",
  "Differential Equations",
  "Physics: Mechanics",
  "Physics: Electromagnetism",
  "Mechanical Engineering Basics",
  "Thermodynamics",
  "Fluid Mechanics",
  "Statistics and Probability",
  "Data Science Bootcamp",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Python Basics",
  "Advanced Python",
  "Web Development Bootcamp",
  "React.js Crash Course",
  "Frontend Web Development",
  "Backend with Node.js",
  "Full Stack MERN",
  "Introduction to Java",
  "Object-Oriented Programming",
  "Data Structures and Algorithms",
  "C++ Programming",
  "Go Language Basics",
  "Rust for Systems Programming",
  "Financial Accounting",
  "Corporate Finance",
  "Microeconomics",
  "Macroeconomics",
  "Introduction to Psychology",
  "Organic Chemistry",
  "Computer Networks",
  "Database Management Systems",
  "Operating Systems"
];
