/**
 * exportPDF.ts
 *
 * Renders a Nextstep project brief as a styled A4 PDF using jsPDF.
 *
 * LAYOUT (top → bottom):
 *   Header bar   – violet bg, "Nextstep" wordmark, course + week sub-line
 *   Section 01   – The Problem        (violet badge)
 *   Section 02   – Starter Scaffold   (teal badge, Courier font, gray bg block)
 *   Section 03   – Checkpoint Qs      (amber badge, numbered list)
 *   Section 04   – Stretch Goal       (rose badge)
 *   Footer       – generation date + "Generated by Nextstep"
 */

import { jsPDF } from "jspdf";
import type { BriefSection } from "../types";
import type { FormInput } from "../types";

interface ExportPDFLabels {
  problem: string;
  scaffold: string;
  checkpoints: string;
  stretch: string;
}

interface ExportPDFOptions {
  labels?: Partial<ExportPDFLabels>;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const PAGE_W  = 210;   // A4 width  (mm)
const PAGE_H  = 297;   // A4 height (mm)
const MARGIN  = 18;    // left / right margin (mm)
const CONTENT_W = PAGE_W - MARGIN * 2;

// Brand colours (as jsPDF RGB arrays)
const VIOLET_BG  : [number,number,number] = [83,  74, 183];  // #534AB7
const VIOLET_TEXT: [number,number,number] = [167, 139, 250];  // violet-400
const TEAL_TEXT  : [number,number,number] = [ 45, 212, 191];  // teal-400
const AMBER_TEXT : [number,number,number] = [251, 191,  36];  // amber-400
const ROSE_TEXT  : [number,number,number] = [251, 113, 133];  // rose-400
const WHITE      : [number,number,number] = [255, 255, 255];
const OFF_WHITE  : [number,number,number] = [220, 220, 230];
const DARK_BG    : [number,number,number] = [ 19,  19,  26];  // #13131A
const CODE_BG    : [number,number,number] = [ 30,  30,  40];
const DIVIDER    : [number,number,number] = [ 50,  50,  65];

type RGB = [number,number,number];

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Set fill colour from an RGB tuple. */
function setFill(doc: jsPDF, rgb: RGB) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}

/** Set draw/stroke colour from an RGB tuple. */
function setDraw(doc: jsPDF, rgb: RGB) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}

/** Set text colour from an RGB tuple. */
function setTextColor(doc: jsPDF, rgb: RGB) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

/**
 * Wraps text to CONTENT_W and prints it, returning the new Y cursor.
 * Automatically inserts page breaks when needed.
 */
function printWrapped(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  opts: { fontSize?: number; lineHeight?: number; color?: RGB; font?: string; fontStyle?: string } = {}
): number {
  const {
    fontSize   = 10,
    lineHeight = 5.5,
    color      = OFF_WHITE,
    font       = "helvetica",
    fontStyle  = "normal",
  } = opts;

  doc.setFont(font, fontStyle);
  doc.setFontSize(fontSize);
  setTextColor(doc, color);

  const lines = doc.splitTextToSize(text, CONTENT_W) as string[];
  for (const line of lines) {
    if (y > PAGE_H - 24) {
      doc.addPage();
      y = MARGIN;
      drawPageBackground(doc);
    }
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

/** Dark background fill for the entire page (matches app theme). */
function drawPageBackground(doc: jsPDF) {
  setFill(doc, DARK_BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
}

/**
 * Draws the violet header bar on the current page.
 * Returns the Y cursor immediately below the header.
 */
function drawHeader(doc: jsPDF, courseName: string, week: number | string): number {
  const HEADER_H = 28;

  // Background bar
  setFill(doc, VIOLET_BG);
  doc.rect(0, 0, PAGE_W, HEADER_H, "F");

  // "Nextstep" wordmark — bold, white, left-aligned
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  setTextColor(doc, WHITE);
  doc.text("Nextstep", MARGIN, 13);

  // "🕯" flame-like separator dot
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  setTextColor(doc, [210, 200, 255]);
  doc.text("✦", MARGIN + 36, 13);

  // Sub-line: course · week
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setTextColor(doc, [210, 200, 255]);
  doc.text(`${courseName}  ·  Week ${week}`, MARGIN, 21);

  return HEADER_H + 10; // y starts 10 mm below the bar
}

/**
 * Draws a coloured section badge (numbered circle + title) and returns
 * the Y cursor below it.
 */
function drawSectionHeader(
  doc: jsPDF,
  label: string,
  title: string,
  color: RGB,
  y: number
): number {
  // Coloured circle badge
  setFill(doc, color.map(v => Math.round(v * 0.25)) as RGB);
  doc.circle(MARGIN + 4, y + 1, 4, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  setTextColor(doc, color);
  doc.text(label, MARGIN + 4, y + 2.2, { align: "center" });

  // Section title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  setTextColor(doc, color);
  doc.text(title, MARGIN + 11, y + 2.5);

  return y + 11;
}

/**
 * Draws a thin horizontal divider rule.
 */
function drawDivider(doc: jsPDF, y: number): number {
  setDraw(doc, DIVIDER);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  return y + 5;
}

/**
 * Draws the footer on the current (last) page.
 */
function drawFooter(doc: jsPDF, courseName: string, week: number | string) {
  const date = new Date().toLocaleDateString("en-AU", {
    day: "numeric", month: "long", year: "numeric",
  });
  const footerY = PAGE_H - 10;

  // Thin top rule
  setDraw(doc, DIVIDER);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, footerY - 4, PAGE_W - MARGIN, footerY - 4);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setTextColor(doc, [120, 120, 150]);
  doc.text(`Generated by Nextstep  ·  ${date}  ·  ${courseName} – Week ${week}`, MARGIN, footerY);
}

// ── Main export function ───────────────────────────────────────────────────────

export function exportBriefAsPDF(brief: BriefSection, formInput: FormInput): void {
  exportBriefAsPDFWithOptions(brief, formInput);
}

export function exportBriefAsPDFWithOptions(
  brief: BriefSection,
  formInput: FormInput,
  options: ExportPDFOptions = {}
): void {
  const { course, week } = formInput;
  const labels: ExportPDFLabels = {
    problem: options.labels?.problem ?? "The Problem",
    scaffold: options.labels?.scaffold ?? "Starter Scaffold",
    checkpoints: options.labels?.checkpoints ?? "Checkpoint Questions",
    stretch: options.labels?.stretch ?? "Stretch Goal",
  };
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ── Page 1 setup ──────────────────────────────────────────────────────────
  drawPageBackground(doc);
  let y = drawHeader(doc, course, week);

  // ── Section 01 – The Problem ──────────────────────────────────────────────
  y = drawSectionHeader(doc, "01", labels.problem, VIOLET_TEXT, y);
  y = printWrapped(doc, (brief.problem || "").trim(), MARGIN, y, {
    fontSize: 10.5,
    lineHeight: 6,
    color: OFF_WHITE,
  });
  y += 4;
  y = drawDivider(doc, y);

  // ── Section 02 – Starter Scaffold ─────────────────────────────────────────
  y = drawSectionHeader(doc, "02", labels.scaffold, TEAL_TEXT, y);

  // Strip markdown code fences if present
  const rawScaffold = (brief.scaffold || "")
    .replace(/^```[\w]*\n?/m, "")
    .replace(/```\s*$/m, "")
    .trim();

  const scaffoldLines = doc.splitTextToSize(rawScaffold, CONTENT_W - 6) as string[];

  // Render code block with pagination support
  let currentY = y + 6;
  let pageStartIdx = 0;
  
  while (pageStartIdx < scaffoldLines.length) {
    if (currentY > PAGE_H - 24) {
       doc.addPage();
       drawPageBackground(doc);
       currentY = MARGIN + 6;
    }

    // Determine how many lines fit on the current page
    let linesOnPage = 0;
    let tempY = currentY;
    while (pageStartIdx + linesOnPage < scaffoldLines.length && tempY <= PAGE_H - 24) {
      linesOnPage++;
      tempY += 4.5;
    }
    
    const blockH = linesOnPage * 4.5 + 4; // add padding

    // Draw background block for this page's chunk
    setFill(doc, CODE_BG);
    setDraw(doc, [60, 60, 80]);
    doc.setLineWidth(0.3);
    doc.roundedRect(MARGIN, currentY - 4, CONTENT_W, blockH, 2, 2, "FD");

    // Draw text
    doc.setFont("courier", "normal");
    doc.setFontSize(8.5);
    setTextColor(doc, [110, 231, 183]); // green-300 for code
    
    let lineY = currentY;
    for (let i = 0; i < linesOnPage; i++) {
      doc.text(scaffoldLines[pageStartIdx + i], MARGIN + 4, lineY);
      lineY += 4.5;
    }

    pageStartIdx += linesOnPage;
    
    if (pageStartIdx < scaffoldLines.length) {
      doc.addPage();
      drawPageBackground(doc);
      currentY = MARGIN + 6;
    } else {
      y = lineY + 2;
    }
  }

  y = drawDivider(doc, y + 2);

  // ── Section 03 – Checkpoint Questions ────────────────────────────────────
  y = drawSectionHeader(doc, "03", labels.checkpoints, AMBER_TEXT, y);
  const checkpoints = brief.checkpoints ?? [];
  for (let i = 0; i < checkpoints.length; i++) {
    if (y > PAGE_H - 24) {
      doc.addPage();
      y = MARGIN;
      drawPageBackground(doc);
    }

    // Number badge
    setFill(doc, [60, 45, 10]);
    doc.circle(MARGIN + 3.5, y + 1, 3.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    setTextColor(doc, AMBER_TEXT);
    doc.text(String(i + 1), MARGIN + 3.5, y + 2.2, { align: "center" });

    // Question text, indented past the badge
    const qLines = doc.splitTextToSize((checkpoints[i] || "").trim(), CONTENT_W - 12) as string[];
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    setTextColor(doc, OFF_WHITE);
    let qY = y;
    for (const qLine of qLines) {
      doc.text(qLine, MARGIN + 10, qY + 2.2);
      qY += 5.5;
    }
    y = qY + 2;
  }
  y += 2;
  y = drawDivider(doc, y);

  // ── Section 04 – Stretch Goal ─────────────────────────────────────────────
  y = drawSectionHeader(doc, "04", labels.stretch, ROSE_TEXT, y);

  // "Challenge" badge
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setFill(doc, [60, 10, 20]);
  doc.roundedRect(MARGIN, y, 22, 5, 1, 1, "F");
  setTextColor(doc, ROSE_TEXT);
  doc.text("CHALLENGE", MARGIN + 11, y + 3.5, { align: "center" });
  y += 8;

  y = printWrapped(doc, (brief.stretch || "").trim(), MARGIN, y, {
    fontSize: 10.5,
    lineHeight: 6,
    color: OFF_WHITE,
  });

  // ── Footer ────────────────────────────────────────────────────────────────
  drawFooter(doc, course, week);

  // ── Save ──────────────────────────────────────────────────────────────────
  const slug = course.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  doc.save(`candela-brief-${slug}-week${week}.pdf`);
}
