/**
 * parseBrief.ts
 *
 * Parses the LLM's raw markdown response into a typed BriefSection object.
 *
 * The LLM is instructed to emit exactly four ## headers.
 * This parser handles both the new (preferred) header names and legacy aliases
 * so that briefs generated by older prompts still display correctly.
 *
 * New (preferred) header names:
 *   ## The Problem
 *   ## Starter Scaffold
 *   ## Checkpoint Questions
 *   ## Stretch Goal
 *
 * Legacy aliases still accepted:
 *   ## Problem  →  maps to "problem"
 *   ## Design Problem  →  maps to "problem"
 *   ## Case Study Problem  →  maps to "problem"
 *   ## Data Scaffold  →  maps to "scaffold"
 *   ## Calculation Scaffold  →  maps to "scaffold"
 *   ## Analysis Checkpoints  →  maps to "checkpoints"
 *   ## Three Checkpoint Questions  →  maps to "checkpoints"
 *   ## Advanced Challenge  →  maps to "stretch"
 *   ## Stretch Goal  →  maps to "stretch"
 *
 * Design:
 *   - Missing sections → empty string / empty array (never throws)
 *   - Extra whitespace → trimmed
 *   - Code blocks inside Scaffold → outer fence stripped, content preserved
 *   - Numbered list items in Checkpoints → extracted as string[]
 */

import { BriefSection } from "../types";

export interface BriefValidationResult {
  isValid: boolean;
  errors: string[];
}

// ── HELPERS ────────────────────────────────────────────────────────────────────

/**
 * Extracts the raw text between a given ## header and the next ## header (or
 * end-of-string). The match is case-insensitive so minor formatting quirks
 * (e.g. trailing spaces) don't break parsing.
 */
function extractSection(raw: string, header: string): string {
  const escaped = header.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(
    `##\\s*${escaped}\\s*\\n([\\s\\S]*?)(?=\\n##|$)`,
    "i"
  );
  const match = raw.match(pattern);
  if (!match) return "";
  return match[1].trim();
}

/**
 * Tries a list of candidate header names in order and returns the first
 * non-empty match. This drives the multi-alias lookup below.
 */
function extractFirstMatch(raw: string, candidates: string[]): string {
  for (const header of candidates) {
    const text = extractSection(raw, header);
    if (text) return text;
  }
  return "";
}

/**
 * Parses a numbered list out of a section string.
 * Matches lines like "1. text", "2. text", "10. text" etc.
 * Returns each item as a trimmed string, stripping the leading number+dot.
 * Returns an empty array when no numbered items are found.
 */
function extractCheckpointItems(sectionText: string): string[] {
  if (!sectionText) return [];
  const lines = sectionText.split("\n");
  const items: string[] = [];
  for (const line of lines) {
    const match = line.match(/^\s*(?:\d+\.\s+|Q[1-3]:\s+)(.+)/i);
    if (match) {
      items.push(match[1].trim());
    }
  }
  return items;
}

function countSentences(text: string): number {
  const matches = text.match(/[^.!?]+[.!?]+(?:\s|$)/g);
  return matches ? matches.length : 0;
}

export function validateBriefSections(brief: BriefSection): BriefValidationResult {
  const errors: string[] = [];

  const problem = brief.problem.trim();
  if (!problem || problem.length <= 100 || countSentences(problem) < 2) {
    errors.push("The Problem must be non-empty, at least 100 characters, and contain at least 2 sentences.");
  }

  const scaffold = brief.scaffold.trim();
  const hasImport = /\b(?:import|from)\b/.test(scaffold);
  const hasFunctionDef = /\bdef\s+[A-Za-z_][A-Za-z0-9_]*\s*\(/.test(scaffold);
  if (!scaffold || !hasImport || !hasFunctionDef) {
    errors.push("Starter Scaffold must include runnable Python-style code with at least one import and one function definition.");
  }

  if (brief.checkpoints.length !== 3) {
    errors.push("Checkpoint Questions must contain exactly 3 items.");
  }
  brief.checkpoints.forEach((checkpoint, index) => {
    if (checkpoint.trim().length < 20) {
      errors.push(`Checkpoint Question ${index + 1} must be at least 20 characters long.`);
    }
  });

  const stretch = brief.stretch.trim();
  if (!stretch || stretch.length <= 30) {
    errors.push("Stretch Goal must be non-empty and longer than 30 characters.");
  }

  return {
    isValid: errors.length === 0,
    errors,
  };
}

/**
 * Strips leading/trailing triple-backtick code fences from a string.
 * Handles optional language tags (e.g. ```python, ```ts) and preserves
 * internal indentation.
 */
function stripCodeFences(text: string): string {
  const withoutOpen = text.replace(/^```[\w]*\s*\n?/, "");
  const withoutClose = withoutOpen.replace(/\n?```\s*$/, "");
  return withoutClose.trim();
}

// ── MAIN EXPORT ────────────────────────────────────────────────────────────────

/**
 * Parses the LLM's raw markdown text into a structured BriefSection.
 *
 * @param rawText - The complete markdown string returned by the LLM.
 * @returns       - A BriefSection with problem, scaffold, checkpoints, stretch.
 */
export function parseBrief(rawText: string): BriefSection {
  // ── Problem ──────────────────────────────────────────────────────────────────
  const problem = extractFirstMatch(rawText, [
    "The Problem",
    "Problem",
    "Design Problem",
    "Case Study Problem",
  ]);

  // ── Scaffold ─────────────────────────────────────────────────────────────────
  const rawScaffold = extractFirstMatch(rawText, [
    "Starter Scaffold",
    "Data Scaffold",
    "Calculation Scaffold",
  ]);
  // Strip outer code fence if the entire scaffold is wrapped in one.
  const scaffold = rawScaffold.startsWith("```")
    ? stripCodeFences(rawScaffold)
    : rawScaffold;

  // ── Checkpoints ───────────────────────────────────────────────────────────────
  const checkpointRaw = extractFirstMatch(rawText, [
    "Checkpoint Questions",
    "Three Checkpoint Questions",
    "Analysis Checkpoints",
  ]);

  // ── Stretch ───────────────────────────────────────────────────────────────────
  const stretch = extractFirstMatch(rawText, [
    "Stretch Goal",
    "Advanced Challenge",
  ]);

  const checkpoints = extractCheckpointItems(checkpointRaw);

  return {
    problem,
    scaffold,
    checkpoints,
    stretch,
  };
}
